<?php
	$states = array(
		'AP' => 'Andhra Pradesh' ,
		'AR' => 'Arunachal Pradesh' ,
		'AS' => 'Assam' ,
		'BR' => 'Bihar' ,
		'DL' => 'Delhi' ,
		'CT' => 'Chattisgarh' ,
		'GA' => 'Goa' ,
		'GJ' => 'Gujarat' ,
		'HR' => 'Haryana' ,
		'HP' => 'Himachal' ,
		'JK' => 'Jammu Kashmir' ,
		'JH' => 'Jharkand' ,
		'KA' => 'Karnataka' ,
		'KL' => 'Kerala' ,
		'MP' => 'Madhya Pradesh' ,
		'MH' => 'Maharashtra' ,
		'MN' => 'Manipur' ,
		'ML' => 'Meghalaya' ,
		'MZ' => 'Mizoram' ,
		'NL' => 'Nagaland' ,
		'OR' => 'Odisha' ,
		'PB' => 'Punjab' ,
		'RJ' => 'Rajasthan' ,
		'SK' => 'Sikkim' ,
		'TN' => 'Tamil Nadu' ,
		'TS' => 'Telangana' ,
		'TR' => 'Tripura' ,
		'UP' => 'Uttar Pradesh' ,
		'UK' => 'Uttarakhand' ,
		'WB' => 'West Bengal' 
		);
?>